apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: lylio-portfolio
spec:
  selector:
    app: lylio-portfolio
  ports:
    - protocol: "TCP"
      port: 80 # The port that the service is running on in the cluster
      targetPort: 80 # The port exposed by the service
  type: LoadBalancer # type of the service. LoadBalancer indicates that our service will be external.
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lylio-portfolio
  labels:
    app: lylio-portfolio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lylio-portfolio
  template:
    metadata:
      labels:
        app: lylio-portfolio
    spec:
      containers:
        - name: lylio-portfolio
          image: lylio/lylio-portfolio:latest
          ports:
            - containerPort: 80 # The port that the container is running on in the cluster
